baseURL = "/"
languageCode = "en-us"
title = "HomotopyContinuation.jl"
theme = "kube"
description = "HomotopyContinuation.jl is a Julia package for solving systems of polynomial equations by numerical homotopy continuation."
Paginate = 8
HighlightJS = true

[Params]
  RSSLink = "/index.xml"
  github = "JuliaHomotopyContinuation" # add your github profile name

  # [Params.section]
  # id = "manual"
  # version = "develop"
  # versionAlias = "7.10"
  # versions = [
  #   "latest",
  #   "develop"
  # ]

[[menu.main]]
    name = "Guides"
    weight = 1
    url = "/guides/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/blog/"
[[menu.main]]
    name = "API Docs"
    weight = 3
    url = "https://juliahomotopycontinuation.github.io/HomotopyContinuation.jl/stable/"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"
[[menu.main]]
    name = "FAQ"
    weight = 5
    url = "/faq/"
