baseURL = "/"
languageCode = "en-us"
title = "HomotopyContinuation.jl"
theme = "kube"
description = "A package for the numerical solution of systems of polynomial equations."
Paginate = 8
HighlightJS = true

[Params]
  RSSLink = "/index.xml"
  github = "JuliaHomotopyContinuation" # add your github profile name

[[menu.main]]
    name = "Guides"
    weight = 1
    url = "/guides/"
[[menu.main]]
    name = "Examples"
    weight = 2
    url = "/examples/"
[[menu.main]]
    name = "Docs"
    weight = 3
    url = "https://juliahomotopycontinuation.github.io/HomotopyContinuation.jl/stable/"
[[menu.main]]
    name = "About"
    weight = 4
    url = "/about/"
[[menu.main]]
    name = "FAQ"
    weight = 5
    url = "/faq/"
[[menu.main]]
    name = "Changelog"
    weight = 7
    url = "/changelog/"

[[menu.main]]
    name = "Github"
    weight = 8
    url = "https://www.github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true